

image: python:3.8

pipelines:
  default:
    - step:
        name: Install dependences
        caches:
          - pip
        script:
          - pip install --upgrade pip
          - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          - pip install flake8 pytest
          - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          - pytest

